apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparrow-api
  name: sparrow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparrow-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparrow-api
    spec:
      containers:
      - image: sparrowdev.azurecr.io/sparrow-api:_BUILD__ID_
        name: sparrow-api
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: PORT
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: APP_ENV 
          - name: APP_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: APP_URL     
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: JWT_SECRET_KEY
          - name: EMAIL_VALIDATION_CODE_EXPIRY_TIME
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: EMAIL_VALIDATION_CODE_EXPIRY_TIME
          - name: JWT_EXPIRATION_TIME
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: JWT_EXPIRATION_TIME
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: DB_URL
          - name: AZURE_CONNECTION_STRING
            valueFrom: 
              secretKeyRef:
                name: sparrow-api-secret
                key: AZURE_CONNECTION_STRING    
          - name: REFRESH_TOKEN_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: REFRESH_TOKEN_SECRET_KEY  
          - name: REFRESH_TOKEN_EXPIRATION_TIME
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: REFRESH_TOKEN_EXPIRATION_TIME
          - name:  REFRESH_TOKEN_MAX_LIMIT
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  REFRESH_TOKEN_MAX_LIMIT
          - name:  SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  SENDER_EMAIL
          - name:  SENDER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  SENDER_PASSWORD
          - name:  LOGIN_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  LOGIN_REDIRECT_URL
          - name:  GOOGLE_APP_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  GOOGLE_APP_URL
          - name:  GOOGLE_ACCESS_TYPE
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  GOOGLE_ACCESS_TYPE
          - name:  GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  GOOGLE_CLIENT_ID
          - name:  GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key:  GOOGLE_CLIENT_SECRET
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: KAFKA_BROKER
                                                                             
---

apiVersion: v1
kind: Service
metadata:
  name: sparrow-api
  labels:
    run: sparrow-api
spec:
  type: ClusterIP
  selector:
    app: sparrow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
